char     *conf_name = "net"; 
fdconf   conf_fds[] = {}; 
uint64_t conf_initscs[][6] = {}; 
scconf   conf_scs[] = { 
    {
        .nr = __NR_socket,
        .args = 3,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_setsockopt,
        .args = 5,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_getsockname,
        .args = 3,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_getsockopt,
        .args = 5,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_connect,
        .args = 3,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_accept,
        .args = 3,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_bind,
        .args = 3,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_read,
        .args = 3,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_write,
        .args = 3,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_recvfrom,
        .args = 3,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_recvmmsg,
        .args = 3,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_recvmsg,
        .args = 3,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_sendmmsg,
        .args = 3,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_sendmsg,
        .args = 4,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_writev,
        .args = 3,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_sendto,
        .args = 6,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_open,
        .args = 3,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_close,
        .args = 1,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_pipe2,
        .args = 2,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_pipe,
        .args = 1,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_clone,
        .args = 2,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_unshare,
        .args = 1,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
    {
        .nr = __NR_setns,
        .args = 2,
        .mask_enabled = 1,
        .mask = {-1, -1, -1, -1, -1, -1},
        .identity_arg = 1,
    },
};
